#!/usr/bin/env bash
# Print the WireGuard .conf for an existing AmneziaWG client.
#
# Usage:  scripts/awg-show-conf.sh <client-name>
#
# Reads awg-data/urls/<client-name>.txt (the vpn:// URL saved by
# awg-add-user.sh), decodes the embedded last_config.config field, and
# prints the raw .conf text on stdout.
#
# Use this when:
#   - the AmneziaVPN app rejects the vpn:// URL form
#   - a client needs a vanilla WireGuard .conf to feed to a different tool
#   - you want to inspect what the URL actually carries
#
# The .conf contains the client's PrivateKey — treat the output as a secret.

set -euo pipefail

usage() {
    cat <<EOF >&2
Usage: $0 <client-name>

Decodes awg-data/urls/<client-name>.txt and prints the embedded WireGuard
.conf to stdout. The output is the exact text that AmneziaVPN's importer
would write to disk when it processes the vpn:// URL.

Redirect to save:
  $0 alice > alice.conf

Or pipe to qrencode for a phone-friendly QR (clients that import .conf via
QR are rarer than vpn://-aware ones, but it works for some):
  $0 alice | qrencode -t ansiutf8
EOF
    exit 1
}

[ $# -eq 1 ] && [ -n "${1:-}" ] || usage
NAME="$1"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
URL_FILE="$REPO_ROOT/awg-data/urls/$NAME.txt"

command -v python3 >/dev/null || { echo "error: python3 not installed" >&2; exit 1; }
[ -f "$URL_FILE" ] || {
    echo "error: $URL_FILE missing — run scripts/awg-add-user.sh first" >&2
    exit 1
}

URL="$(cat "$URL_FILE")"

python3 - "$URL" <<'PY_EOF'
import sys, base64, zlib, json

url = sys.argv[1].strip()
if not url.startswith("vpn://"):
    sys.exit("error: file does not start with vpn://")

payload = url[len("vpn://"):]
payload += "=" * (-len(payload) % 4)

# Try standard base64 first (what the current script emits); fall back to
# URL-safe in case the file was generated by an earlier version of the script.
try:
    raw = base64.b64decode(payload)
except Exception:
    raw = base64.urlsafe_b64decode(payload)

# Qt qCompress: 4-byte BE uncompressed length + zlib stream.
data = zlib.decompress(raw[4:])
outer = json.loads(data)

awg = outer.get("containers", [{}])[0].get("awg") or {}
last_config = awg.get("last_config")
if not last_config:
    sys.exit("error: vpn:// payload has no last_config field")

# last_config is a JSON-encoded string itself; the raw .conf lives under "config".
inner  = json.loads(last_config)
config = inner.get("config")
if not config:
    sys.exit("error: last_config has no 'config' field (schema mismatch?)")

sys.stdout.write(config)
if not config.endswith("\n"):
    sys.stdout.write("\n")
PY_EOF
